In [1]:
import pandas as pd

In [3]:
books_df = pd.read_csv('bestsellers-with-categories.csv', sep=',', header=0, names=['Nombre', 'Autor', 'Calificación', 'Reviews', 'Precio', 'Año', 'Género'])
books_df.head(2)

,Nombre,Autor,Calificación,Reviews,Precio,Año,Género
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction

In [5]:
def two_times(value):
    return value * 2

In [6]:
books_df['Calificación'].apply(two_times)

0      9.4
1      9.2
2      9.4
3      9.4
4      9.6
      ...
545    9.8
546    9.4
547    9.4
548    9.4
549    9.4
Name: Calificación, Length: 550, dtype: float64

In [7]:
books_df['Rating_2'] = books_df['Calificación'].apply(two_times)
books_df

,Nombre,Autor,Calificación,Reviews,Precio,Año,Género,Rating_2
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction,9.4
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction,9.2
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction,9.4
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction,9.4
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction,9.6
...,...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction,9.8
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction,9.4
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction,9.4
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction,9.4
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction,9.4

In [10]:
books_df['Rating_2'] = books_df['Calificación'].apply(lambda x : x * 3)
books_df

,Nombre,Autor,Calificación,Reviews,Precio,Año,Género,Rating_2
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction,14.1
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction,13.8
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction,14.1
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction,14.1
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction,14.4
...,...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction,14.7
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction,14.1
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction,14.1
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction,14.1
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction,14.1

In [14]:
books_df['Rating_2'] = books_df.apply(lambda x : x['Calificación'] * 2 if x['Género']=='Fiction' else x['Calificación'], axis=1)
books_df

,Nombre,Autor,Calificación,Reviews,Precio,Año,Género,Rating_2
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction,4.7
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction,9.2
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction,4.7
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction,9.4
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction,4.8
...,...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction,9.8
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction,4.7
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction,4.7
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction,4.7
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction,4.7